version: '3.8'
services:
  stats-server:
    build: ./stats-server
    image: stats_service_image
    container_name: stat_service_container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=ExploreWithMeStat
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: postgres_emw_stat_container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ExploreWithMeStat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: main_service_image
    container_name: main_service_container
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=ExploreWithMe
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres_emw_container
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ExploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root